### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by claudio-moya** [rakuten-rex/radio-button#1]
Stories

- [x] Turn `disabled` false
https://github.com/rakuten-rex/radio-button/blob/e64a70c2a05443095a941210815bb7dae170a871/src/Radio/Radio.stories.jsx#L55
- [x] Use one tab for Theme Color:
https://github.com/rakuten-rex/radio-button/blob/e64a70c2a05443095a941210815bb7dae170a871/src/Radio/Radio.stories.jsx#L117-L136

From
```
const themeColor = color(
    'Checkbox theme color',
    '#bf0000',
    'Checkbox theme color'
  );
```
to
```
const themeColor = color(
    'Checkbox theme color',
    '#bf0000',
    'Theme Colors'
  );
```
- [x] Remove unused css props
https://github.com/rakuten-rex/radio-button/blob/e64a70c2a05443095a941210815bb7dae170a871/src/Radio/_Radio.mixin.scss#L10-L11
- [x] Update example component name 
https://github.com/rakuten-rex/radio-button/blob/develop/project-scripts/webpack/markdown/EXAMPLE_JSX.md

from
```
import MyComponent from '@rakuten-rex/__COMPONENT_NAME__';
```

to
```
import Radio from '@rakuten-rex/__COMPONENT_NAME__';
```
- [x] Update path for sass in Vue example
https://github.com/rakuten-rex/radio-button/blob/develop/project-scripts/webpack/markdown/README.md

from
```
<style scoped>
@import "~@rakuten-rex/__COMPONENT_NAME__/css";
</style>
```

to
```
<style scoped>
@import "~@rakuten-rex/__COMPONENT_NAME__/Radio/css";
</style>
```

**Comment by claudio-moya** [comment]
- [ ] Remove unused css props
https://github.com/rakuten-rex/radio-button/blob/e64a70c2a05443095a941210815bb7dae170a871/src/Radio/_Radio.mixin.scss#L10-L11

**Comment by claudio-moya** [comment]
- [ ] Update example component name 
https://github.com/rakuten-rex/radio-button/blob/develop/project-scripts/webpack/markdown/EXAMPLE_JSX.md

from
```
import MyComponent from '@rakuten-rex/__COMPONENT_NAME__';
```

to
```
import Radio from '@rakuten-rex/__COMPONENT_NAME__';
```

**Comment by claudio-moya** [comment]
- [ ] Update path for sass in Vue example
https://github.com/rakuten-rex/radio-button/blob/develop/project-scripts/webpack/markdown/README.md

from
```
<style scoped>
@import "~@rakuten-rex/__COMPONENT_NAME__/css";
</style>
```

to
```
<style scoped>
@import "~@rakuten-rex/__COMPONENT_NAME__/Radio/css";
</style>
```

**Comment by claudio-moya** [comment]
- [ ] File names for build should be lowercase for HTML example
https://github.com/rakuten-rex/radio-button/blob/develop/project-scripts/webpack/markdown/README.md

from
```
https://unpkg.com/@rakuten-rex/radio-button@0.0.1/Radio/Radio.production.min.css
```
to
```
https://unpkg.com/@rakuten-rex/radio-button@0.0.1/Radio/radio.production.min.css
```

**Comment by claudio-moya** [comment]
- [ ] Fix prop name from `area-` to `aria-`
https://github.com/rakuten-rex/radio-button/blob/41a7b092d7e0c2f0b553c9f9f56c3dec424f5bb4/src/Radio/Radio.jsx#L34
https://github.com/rakuten-rex/radio-button/blob/41a7b092d7e0c2f0b553c9f9f56c3dec424f5bb4/src/RadioGroup/RadioGroup.stories.jsx#L30
https://github.com/rakuten-rex/radio-button/blob/41a7b092d7e0c2f0b553c9f9f56c3dec424f5bb4/src/RadioGroup/RadioGroup.jsx#L39
https://github.com/rakuten-rex/radio-button/blob/41a7b092d7e0c2f0b553c9f9f56c3dec424f5bb4/src/RadioGroup/RadioGroup.jsx#L63
- [ ] Use a unique key instead of value, something like this:
```jsx
{options.map( (option, index) => (
<Radio key={`rex-radio-key-${index}-${value.toString()}`} />
))}
```
https://github.com/rakuten-rex/radio-button/blob/41a7b092d7e0c2f0b553c9f9f56c3dec424f5bb4/src/RadioGroup/RadioGroup.jsx#L31

Stories
- [ ] Add knobs in Dynamic props story: text, id, label,  value, className, aria-label
- [ ] Remove unused addons (action, select)

**Comment by montomos** [comment]
> * [x]  Fix prop name from `area-` to `aria-`
>   https://github.com/rakuten-rex/radio-button/blob/41a7b092d7e0c2f0b553c9f9f56c3dec424f5bb4/src/Radio/Radio.jsx#L34
>   
>   https://github.com/rakuten-rex/radio-button/blob/41a7b092d7e0c2f0b553c9f9f56c3dec424f5bb4/src/RadioGroup/RadioGroup.stories.jsx#L30
>   
>   https://github.com/rakuten-rex/radio-button/blob/41a7b092d7e0c2f0b553c9f9f56c3dec424f5bb4/src/RadioGroup/RadioGroup.jsx#L39
>   
>   https://github.com/rakuten-rex/radio-button/blob/41a7b092d7e0c2f0b553c9f9f56c3dec424f5bb4/src/RadioGroup/RadioGroup.jsx#L63
> * [ ]  Use a unique key instead of value, something like this:
> 
> ```js-jsx
> {options.map( (option, index) => (
> <Radio key={`rex-radio-key-${index}-${value.toString()}`} />
> ))}
> ```
@claudio-moya error: Do not use Array index in keys in keyseslint(react/no-array-index-key)"
> 
> https://github.com/rakuten-rex/radio-button/blob/41a7b092d7e0c2f0b553c9f9f56c3dec424f5bb4/src/RadioGroup/RadioGroup.jsx#L31
> 
> * [ ]  Don't overwrite `type` prop
>   https://github.com/rakuten-rex/radio-button/blob/41a7b092d7e0c2f0b553c9f9f56c3dec424f5bb4/src/RadioGroup/RadioGroup.jsx#L30
> 
> Stories
> 
> * [ ]  Add knobs in `Dynamic Props` story: text, id, label,  value, className, aria-label
> * [ ]  Remove unused addons (action, select)
> * [ ]  Create new story `Dynamic Props` for Radio Group and add knobs to test array in RadioGroup, example:
> 
> ```
> Quantity of items: number
> id: text
> name: text
> value:  text
> ...
> ```
> 
> Based on `Quantity of items` you can create an array with the props (id, name, value, etc.) and add an index to each item to create a list of items, example:
> 
> ```js-jsx
> const quantity = number('Quantity of items')
> const id = text('ID')
> const options = quantity.map(index => {
> return {
>  id: `${id}-${index}`,
> ...
> }
> })
> ```
> 
> expected result:
> 
> ```js-jsx
> <RadioGroup options={[
> {
>   id: 'my-id-1',
> ...
> },
> {
>   id: 'my-id-2',
> ...
> }
> ]} 
> />
> ```
