### ISSUE TITLE
BrowserStack QA

### ISSUE THREAD

**Issue by claudio-moya** [rakuten-rex/radio-button#5]
## Radio Button
- [x] Default
https://rakuten-rex.github.io/radio-button/iframe.html?id=radio-uncontrolled--default-view
- [x] Checked
https://rakuten-rex.github.io/radio-button/iframe.html?id=radio-uncontrolled--checked-view
- [x] Disabled
https://rakuten-rex.github.io/radio-button/iframe.html?id=radio-uncontrolled--disabled-view
- [x] Inline
https://rakuten-rex.github.io/radio-button/iframe.html?id=radio-group-controlled--layout-inline
- [x] Block
https://rakuten-rex.github.io/radio-button/iframe.html?id=radio-group-controlled--layout-block
- [x] Inline mixed
https://rakuten-rex.github.io/radio-button/iframe.html?id=radio-uncontrolled--layout-inline&knob-Quantity%20of%20items=5&knob-layout%20(Block/Inline)=true&knob-label=cat&knob-id=cat&knob-name=pet&knob-value=cat
- [x] Block mixed
https://rakuten-rex.github.io/radio-button/iframe.html?id=radio-uncontrolled--layout-block&knob-Quantity%20of%20items=5&knob-layout%20(Block/Inline)=true&knob-label=cat&knob-id=cat&knob-name=pet&knob-value=cat
- [x] Theme
https://rakuten-rex.github.io/radio-button/iframe.html?id=radio-uncontrolled--with-theme-react-and-css-vars

**Comment by montomos** [comment]
All cases have issues on Windows 10 ie 11

Default
![win10_ie_11 0](https://user-images.githubusercontent.com/1501667/75307304-c2802600-588e-11ea-89b2-d414997dce49.png)
Disabled
![win10_ie_11 0](https://user-images.githubusercontent.com/1501667/75307315-c90e9d80-588e-11ea-9a00-1b1fec96c27f.png)
Inline
![win10_ie_11 0 (1)](https://user-images.githubusercontent.com/1501667/75307335-d461c900-588e-11ea-8f05-d0d696163e9f.png)

Inline-mixed
![win10_ie_11 0](https://user-images.githubusercontent.com/1501667/75307374-e479a880-588e-11ea-9928-e8f12297e782.png)

Block
![win10_ie_11 0 (1)](https://user-images.githubusercontent.com/1501667/75307289-b4caa080-588e-11ea-8165-e4b92373ec4e.png)
Block mixed
![win10_ie_11 0](https://user-images.githubusercontent.com/1501667/75307277-ae3c2900-588e-11ea-91f6-d848d30d4d1e.png)
Theme
![win10_ie_11 0](https://user-images.githubusercontent.com/1501667/75307267-a9777500-588e-11ea-9f42-bc4ddc1a9374.png)
